name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: make test
